# Token reminder: github > settings > developer > generate > copy on clipoard
# On travis: assign the clipboard to GH_REPO_TOKEN
language: sh

# latest distribution
# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# just master branch (verify branch name)
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# environment must be defined
# one build will be triggered for each line in the env array.
env:
  - TRAVISENVIRONMENT=yes

# script to execute
script:
 - ./makeDoxy

# Generate and deploy documentation
#
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

