language: sh

# latest ubuntu
# https://docs.travis-ci.com/user/reference/overview/
# Tutorial: https://gist.github.com/vidavidorra/548ffbcdae99d752da02
dist: bionic

# just main branch
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - graphviz

# script to execute
script:
 - ./makeDoxy

# Generate and deploy documentation
#
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master

