#!/bin/bash

# Purpose: creates the doxygen documentation for all the glibraries
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Doxygen version: "$(doxygen --version)
echo " "

cd ../glibrary

if [ -d $ddir ]
then
	rm -rf $ddir
fi
mkdir -p $ddir

echo " "Creating gemc doxygen documentation
doxygen Doxyfile
echo " "
