#!/bin/bash

# Purpose: creates the doxygen documentation for all the glibraries
# This script is used by TRAVIS
#
# Arguments: none

echo " "
echo " Doxygen version: "$(doxygen --version)
echo " "

git clone https://github.com/gemc/glibrary.git

./glibrary/createDoxyfile
./glibrary/makeDoxyfileForLibrary gemc

echo " "Creating gemc doxygen documentation
doxygen Doxyfile
echo " "
