# This compiles the example(s). The library is an header include
from init_env import init_environment

# load needed environment for the example
env = init_environment('glibrary')
env.Append(CXXFLAGS=['-std=c++20'])

# standard pre and suffix for gemc plugins
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")

ford_dll  = env.SharedLibrary( source = 'factoryExample/FordFactory.cc',  target = 'fordFactory')
tesla_dll = env.SharedLibrary( source = 'factoryExample/TeslaFactory.cc', target = 'teslaFactory')

sources = [
			  'factoryExample/example.cc',
			  'factoryExample/ShapeFactory.cc'
			  ]

example = env.Program(source = sources, target = 'example')

