Import('env')

env.Prepend(LIBS = 'gsd')

sources = [
	'gsd.cc',
	'decisionToSkipHit.cc'
	]

# The # in the LIBPATH directories specify that they’re relative to the top-level directory
env.Library(source = sources, target = "#lib/gsd")


