Import('env')

env.Prepend(LIBS = 'gutilities')

sources = Split("""
	gemcUtilities.cc
	defineOptions.cc
	""")

# The # in the LIBPATH directories specify that they’re relative to the top-level directory
env.Library(source = sources, target = "#lib/gutilities")


