#pragma once

#define GPARTICLENOTDEFINED (-999)

// error codes in the 900s
#define ERR_GPARTICLENOTFOUND        901
#define ERR_GPARTICLEWRONGTHETAMODEL 902
#define ERR_GPARTICLETABLENOTFOUND   903
