#ifndef  GSTREAMER_H_CONVENTIONS
#define  GSTREAMER_H_CONVENTIONS 1

// exit codes: 800s
#define EC__GSTREAMERFACTORYNOTFOUND  801
#define EC__GSTREAMERVARIABLEEXISTS   802

#define EVTLOGHEADER   " ⊳ "
#define SROLOGHEADER   " ⊪ "

#endif
