#pragma once

// exit codes: 800s
#define ERR_GSTREAMERFACTORYNOTFOUND  801
#define ERR_GSTREAMERVARIABLEEXISTS   802
#define ERR_CANTOPENOUTPUT            803
#define ERR_CANTCLOSEOUTPUT           804
