# This compiles the example and the gstreamer (if it's not built already)
from init_env import init_environment

# load needed environment for this library
# added xercesc for posix compatibility
env = init_environment('glibrary clhep geant4 xercesc')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# build the factories. Notice: the environment are not passed
# but individually loaded in each plugin
libsTextDLL    = SConscript('SConscriptTEXTDLL')
libsRootDLL    = SConscript('SConscriptROOTDLL')
libsJlabSRODLL = SConscript('SConscriptJLABSRODLL')


# example(s)
# ----------
#
# manually appending this library so the example can be compiled
env.Append(LIBS = 'gstreamer')

# builds the example
example = env.Program(source = 'example.cc', target = 'example')

# example(s) depend on the library existance
Depends(example,  lib);
