Import('env')

env.Prepend(LIBS = 'gui')

sources = [
			  'gui.cc',
			  'leftButtons.cc',
			  'rightContent.cc',
			  'topLayout.cc'
			  ]

# The # in the LIBPATH directories specify that they’re relative to the top-level directory
env.Library(source = sources, target = "#lib/gui")
