# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# example(s)
# ----------
#
# manually appending this library so the example can be compiled
env.Append(LIBS = 'goptions')


# builds the example(s)
simpleExample              = env.Program(source = 'examples/simple.cc',                target = 'simpleExample')
structuredExample          = env.Program(source = 'examples/structured.cc',            target = 'structureExample')
cumulativeStructureExample = env.Program(source = 'examples/cumulative_structured.cc', target = 'cumulativeStructureExample')
# cumulativeStructureExample = env.Program(source = 'examples/advanced.cc',              target = 'advanced')

# example(s) depend on the library existance
Requires(simpleExample,              lib);
Requires(structuredExample,          simpleExample);
Requires(cumulativeStructureExample, structuredExample);
