# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

sources = [
			  'goption.cc',
			  'goptions.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/goptions')
