# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

sources = [
			  'g4volume.cc',
			  'g4world.cc',
			  'g4systemOptions.cc',
			  'g4objectsFactories/geant4Dependencies.cc',
			  'g4objectsFactories/g4objectsCreators.cc',
			  'g4objectsFactories/g4native/g4SolidConstructorDescription.cc',
			  'g4objectsFactories/g4native/checkAndReturnParameters.cc',
			  'g4objectsFactories/g4native/buildSolid.cc',
			  'g4objectsFactories/g4native/buildLogical.cc',
			  'g4objectsFactories/g4native/buildPhysical.cc',
			  'g4objectsFactories/cad/buildSolid.cc',
			  'g4objectsFactories/cad/buildLogical.cc',
			  'g4objectsFactories/cad/buildPhysical.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/g4system')
