Import('env')

env.Prepend(LIBS = 'gdetector')

sources = [
	'gdetectorConstruction.cc'
	]

# The # in the LIBPATH directories specify that they’re relative to the top-level directory
env.Library(source = sources, target = "#lib/gdetector")


