Import('env')

env.Prepend(LIBS = 'eventaction')

sources = [
			  'gEventAction.cc',
			  'gEventActionLog.cc'
			  ]

# The # in the LIBPATH directories specify that they’re relative to the top-level directory
env.Library(source = sources, target = "#lib/eventaction")


