# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

sources = Split("""
	gfields.cc
	""")

env = init_environment("")

# destination library is one dir up
lib = env.Library(source = sources, target = "../lib/gfields")
