# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# example(s)
# ----------
#
# manually appending this library so the example can be compiled
env.Append(LIBS = 'gtouchable')

# builds the example(s)
example = env.Program(source = 'example.cc', target = 'example')

# example(s) depend on the library existance
Requires(example,  lib)
