# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('qt5 glibrary')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# example(s)
# ----------
#
# manually appending this library so the example can be compiled
env.Append(LIBS = 'gsplash')

# builds the example(s)
exampleSources = [
						'example.cc',
						'example.qrc'
						]

example = env.Program(source = exampleSources, target = 'example')

# example(s) depend on the library existance
Depends(example, lib);
