#ifndef  G4DISPLAY_H_CONVENTIONS
#define  G4DISPLAY_H_CONVENTIONS 1

#define GDEFAULTVIEWERDRIVER  "OGL"
#define GDEFAULTVIEWERSIZE    "1200x1200"
#define GDEFAULTVIEWERPOS     "-400+100"
#define GDEFAULTVSEGPERCIRCLE 50


extern std::vector<std::string> AVAILABLEG4VIEWERS;

#endif
