# This compiles the example and the g4display (if it's not built already)
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary geant4 clhep qt5')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# example(s)
# ----------
#
# manually appending this library so the example can be compiled
env.Append(LIBS = 'g4display')
