# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

sources = [
			  'g4displayOptions.cc',
			  'g4SceneProperties.cc',
			  'g4Text.cc',
			  'g4controls.cc',
			  'tabs/g4displaycamera.cc',
			  'tabs/g4displayslice.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/g4display')
