# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary clhep geant4')

# we build the library in ../lib
# by default, targets outside the current tree are not selected.
env.Default('../')

# build the library
lib = SConscript('SConscript', exports='env')

# standard pre and suffix for gemc plugins
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")

ctof_dll  = env.SharedLibrary( source = 'ctofRoutinesExample.cc',  target = 'ctofRoutinesExample')
Depends(ctof_dll,  lib);


example = env.Program(source = 'example.cc', target = "example")

Depends(example,  ctof_dll);
