# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

# local directories include
env.Append(CPPPATH = [Dir('event'), Dir('frame')])

sources = [
			  'event/gDigitizedData.cc',
			  'event/gTrueInfoData.cc',
			  'event/gDataCollection.cc',
			  'event/gEventDataCollectionHeader.cc',
			  'event/gEventDataCollection.cc',
			  'frame/gIntegralPayload.cc',
			  'frame/gFrameDataCollectionHeader.cc',
			  'frame/gFrameDataCollection.cc'
			  ]

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/gdata')
