#!/usr/bin/env python3

import subprocess
import os
import shutil


def run_config(command, option):
	"""Run a config command with the given option and return the output."""
	result = subprocess.run([command, option], capture_output=True, text=True, check=True)
	return result.stdout.strip()


def filter_unwanted_flags(flags):
	"""Remove unwanted flags related to Qt, CLHEP, and XercesC."""
	# unwanted = ["CLHEP", "clhep", "xercesc", "XercesC", "TreePlayer", "-Wshadow"]
	unwanted = ["Qt", "qt", "CLHEP", "clhep", "xercesc", "XercesC", "TreePlayer", "-Wshadow"]
	return " ".join(flag for flag in flags.split() if not any(uw in flag for uw in unwanted))


def filter_root_flags(flags, root_libs):
	"""Keep only specified ROOT libraries."""
	return " ".join(flag for flag in flags.split() if "-L" in flag or any(f"-l{lib}" in flag for lib in root_libs))


def generate_pkgconfig(config_cmd, output_filename, name, description, root_lbs=None):
	"""Generate a .pc file for pkg-config."""
	prefix = run_config(config_cmd, "--prefix")
	libs = filter_unwanted_flags(run_config(config_cmd, "--libs"))
	cflags = filter_unwanted_flags(run_config(config_cmd, "--cflags"))
	version = run_config(config_cmd, "--version")

	if config_cmd == "root-config" and root_lbs:
		libs = filter_root_flags(libs, root_lbs)
	else:
		libs = filter_unwanted_flags(libs)
		cflags = filter_unwanted_flags(cflags)

	pc_content = f"""
prefix={prefix}
exec_prefix=${{prefix}}
libdir=${{prefix}}/lib
includedir=${{prefix}}/include
   
Name: {name}
Description: {description}
Version: {version}
Cflags: {cflags}
Libs:  {libs}
    """.strip()

	# Write to the .pc file
	pc_file_path = os.path.join(os.environ["GEMC"], "lib", "pkgconfig", output_filename)
	os.makedirs(os.path.dirname(pc_file_path), exist_ok=True)
	with open(pc_file_path, "w") as pc_file:
		pc_file.write(pc_content + "\n")

	print(f"Generated {pc_file_path}")


def check_root_config():
	"""Check if root-config is available."""
	return shutil.which("root-config") is not None


# generate_geant4_package_cache is no longer necessary if the package cache is generated by the Geant4 CMake build system
if __name__ == "__main__":
	generate_pkgconfig("geant4-config", "geant4.pc", "Geant4", "Geant4 Simulation Toolkit")
	if check_root_config():
		root_list = ["RIO", "Tree", "Core", "root"]
		generate_pkgconfig("root-config", "root.pc", "ROOT", "ROOT Data Analysis Framework", root_list)
