#ifndef  EVENTDISPENSER_H_CONVENTIONS
#define  EVENTDISPENSER_H_CONVENTIONS 1

#define EVENTDISPENSERLOGMSGITEM  " ⋿"

// error codes in the 700s
#define EC__EVENTDISTRIBUTIONFILENOTFOUND 701

#endif
