# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

env.Append(CPPPATH = [Dir('gsystemFactories'), Dir('gsystemFactories/cad'), Dir('gsystemFactories/text'), Dir('gsystemFactories/gdml'), Dir('gsystemFactories/sqlite')])

sources = [
			  'gvolume.cc',
			  'gmaterial.cc',
			  'gsystem.cc',
			  'gworld.cc',
			  'gsystemOptions.cc',
			  'gsystemFactories/text/systemTextFactory.cc',
			  'gsystemFactories/text/loadMaterials.cc',
			  'gsystemFactories/text/loadGeometry.cc',
			  'gsystemFactories/cad/systemCadFactory.cc',
			  'gsystemFactories/cad/loadMaterials.cc',
			  'gsystemFactories/cad/loadGeometry.cc',
			  'gsystemFactories/gdml/systemGdmlFactory.cc',
			  'gsystemFactories/gdml/loadMaterials.cc',
			  'gsystemFactories/gdml/loadGeometry.cc',
			  'gsystemFactories/sqlite/systemSqliteFactory.cc',
			  'gsystemFactories/sqlite/loadMaterials.cc',
			  'gsystemFactories/sqlite/loadGeometry.cc'
			  ]

env.Append(LIBS = 'sqlite3')

# destination library is one dir up - relative to this SConscript
lib = env.Library(source = sources, target='../lib/gsystem')
