# called from the local SConstruct or
# the glibrary SConstruct one dir up
Import('env')
env.Append(CXXFLAGS=['-std=c++20'])

sources = [
			  'gphysics.cc',
			  'gphysicsOptions.cc'
			  ]

# destination library is one dir up - relative to this SConscript
# this will ensure that the main glibrary SConstructs aknowledge the
# gphysics object as 'install' instead of just the library build
lib = env.Library(source = sources, target='gphysics')
env.Install('../lib', lib)
