name: Almalinux Build

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build gemc
        run: |
          ./ci/build.sh none


