name: Ubuntu Build
permissions:
  contents: read
  pull-requests: write

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    container:  jeffersonlab/geant4:g4v11.3.2-ubuntu24

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Fix Ownership
        run: |
          # recent versions of Git refuse to touch a repository whose on-disk owner 
          # doesn’t match the UID that is running the command
          # mark the workspace (and any nested path) as safe
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"/src
      - name: Build gemc
        run: |
          ./ci/build.sh none
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: logs-ubuntu
          path: |
            /root/src/logs