name: Ubuntu Build
permissions:
  contents: read
  pull-requests: write

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    container:  jeffersonlab/geant4:g4v11.3.0-ubuntu24

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Fix Ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          #chown -R $(id -u):$(id -g) $PWD
          #git fetch --prune --unshallow --tags
          git config --global --add safe.directory '*'
      - name: Build gemc
        run: |
          ./ci/build.sh none
