# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
name: gemc

on:
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize
jobs:
  validation_job:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0
    name: ${{ matrix.dir }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: examples/geometry/dosimeter
            script: example.py
            gcard: example.jcard
          - dir: examples/geometry/simple_flux
            script: example.py
            gcard: example.jcard
          - dir: examples/plugins/calorimeter
            script: example.py
            gcard: example.jcard
          - dir: projects/clas12/targets
            script: targets.py
            gcard: target.jcard
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@main
      - name: Run ci.sh
        run: |
          ./ci.sh "${{ matrix.dir }}" "${{ matrix.script }}" "${{ matrix.gcard }}"
