name: Build, SciG Tests

on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testSciG:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc3:1.0
    name: Run ${{ matrix.examples }}
    strategy:
      fail-fast: false
      matrix:
        examples:
          - examples/dosimeter
          - examples/simple_flux
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@main
      - name: Build, Test ${{ matrix.examples }}
        run: |
          ./ci/testSciG.sh -e ${{ matrix.examples }} 
